// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:kitabu/models/library_item.dart';
import 'package:kitabu/models/media.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadRecordAdapter());
    registerAdapter(MediaFileHiveAdapter());
    registerAdapter(MediaHiveAdapter());
    registerAdapter(WatchedItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadRecordAdapter());
    registerAdapter(MediaFileHiveAdapter());
    registerAdapter(MediaHiveAdapter());
    registerAdapter(WatchedItemAdapter());
  }
}
